### PR TITLE
+ python3 compatibility, + setup() method

### PR DESCRIPTION
**Pull request by MasterAler**
I just used 2to3 script and added setter, which needed badly. Could be useful in case someone stores keys as strings somewhere.
Seems that backward compatibility is not broken, checked in python 2.7.

Try any of this if you find it useful. Sorry if I'm bothering you too much, just came across the problem where your library is required a lot =)

### CODE REVIEW

**Comment by heinzK1X** [comment]
Many thanks for your work! I will merge it. 
But, I feel that the names `lookup` and `setup` are ok, but `get` and `set`would be nicer. I'll add aliases after merging. 
What project are you working on? =)

**Comment by heinzK1X** [comment]
Hi. I just pushed the changes. Could you verify them? On py2.7 the tests are all ok.
Please note, that I changed the implementation a bit. `setup(..)` now parses the value, which means that you can also setup lists, arrays and groups with it. It also returns a Boolean to state if the action was successful.
I boldly increased the version number to 0.2 with this new feature.. =)

**Comment by MasterAler** [comment]
Sorry for responding only now, have been away for a while without Internet.

With the value parsing and a boolean result the feature looks great, tested on my py3.4, everything seems to work fine. By the way, you might consider to name 'private' methods with two underscores, like `__lookup`. Not significant at all, just seen it somewhere in PEP resently.

About my project: a good fellow, working as a scientist (physicist to be exact) is performing some complex calculations and asked for help in optimising their lab scripts, making everything more automated. The input data is in the libconfig format and I was not eager to use C++ only because of that. Your library came in handy =)

Verified the update using current working code, is it sufficient or would you like some unittests?

**Comment by heinzK1X** [comment]
Hi, thanks a lot!
Funny, I'm a physicist, too. But I wrote the lib for a mumble plugin in arkos, where we have a python backend, but libconfig is used in umurmur.
The unittests are there, if you could simply try to run them it would be nice. But I think it's sufficient, nevermind. =)
Cheers

**Comment by MasterAler** [comment]
Yeah, I've seen those and already run, they pass for sure.
Oh, just saw your other account with 'CERN' in it =)

Will be happy to see your update on pypi )

**Comment by HeinAtCERN** [comment]
Yeah. It's complicated to have two github accounts.. The cern one is actually supposed for work. 
Thanks for reminding me, I almost forgot to upload to PyPI again.

**Pull request merged**
