### PR TITLE
Travis CI

### PR DESCRIPTION
**Pull request by marbre**
I finally managed it to setup a `.travis.yml`, which should probably work. Python 2.7, 3.3 and 3.4 are tested. I further converted the `README.rst` to markdown, to embedded the build status. The next step would be to register the project for travis.

### CODE REVIEW

**Comment by HeinAtCERN** [comment]
Hi marbre, thanks a lot. Is there no way to have the rst file with travis? The rst format is required for PyPI...

**Comment by marbre** [comment]
Well, just stick with the README.rst. I just switched to markdown because the build status can be embedded as HTML link. This isn't needed anyway for pypi.

**Comment by marbre** [comment]
So, how to proceed here? Should I `push force` to get rid of the README.md?

**Comment by HeinAtCERN** [comment]
Hi. Sorry I didn't have to look into this. If you'd remove the readme, I'll hit the merge button. =) Cheers!

**Comment by marbre** [comment]
@HeinAtCERN Done :) I think it's still needed to register for travis-ci.

**Comment by HeinAtCERN** [comment]
Yes, I will do this as soon as possible. =)

**Comment by HeinAtCERN** [comment]
Done. =)

**Pull request merged**
