### PR TITLE
fix reading long integers with Python3.x

### PR DESCRIPTION
**Pull request by jerome-jh**
Added a test.

### CODE REVIEW

**Comment by jerome-jh** [comment]
Hey HeinerTholen,
Did you notice I submitted a new pull request a bit more like you suggested, checking the Python interpreter version? Do you plan to merge it? Maybe it is not leptonic enough or lacks a few GeV.
BR,
Jerome.

**Comment by HeinerTholen** [comment]
leptonic enough? haha, so you're not in particle physics... =)
It's cool, thanks a lot. I had a lot of stress last week, so that's why I couldn't take my time for looking into it.

One more thing might be cool, if you care about it: When you have a long integer in python3, it should also be written out with an L, right? Otherwise we loose precision when writing a config.

**Comment by jerome-jh** [comment]
> leptonic enough? haha, so you're not in particle physics... =)

Absolutely not, far too abstract for me.

> When you have a long integer in python3, it should also be written out with an L, right? Otherwise we loose precision when writing a config.

hum ... it's not that we loose precision, but the config file will be illegal in some sense, because python3 will not output an L for long integers, as python2 does (just checked that). It is not that simple to fix because for arrays of long, every value should be suffixed with L, not just those that are "large enough".
I'm afraid that would require introducing a new type ConfLong just like you did for ConfArray, ConfList, ConfGroup.
Nice exercise, but no time to do it right now :)

**Comment by HeinerTholen** [comment]
Good point, thanks for bringing it up.

Yes, and many thanks, again, for contributing.  Nice work!

**Pull request merged**
